apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-deployment
  namespace: resnet-tf
spec:
  selector:
    matchLabels:
      app: resnet-tfserver
  replicas: 1
  template:
    metadata:
      labels:
        app: resnet-tfserver
    spec:
      containers:
      - name: resnet-container
        image: 172.30.0.49:5000/tensorflow-serving/resnet
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: resnet-service
  name: resnet-service
  namespace: resnet-tf
spec:
  ports:
  - port: 8500
    targetPort: 8501
  selector:
    app: resnet-tfserver
  type: ClusterIP
