apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: resnet-tf-jobpipeline
spec:
  containers:
  - name: helloworld
    image: helloworld
    volumeMounts:
    - name: data-path
      mountPath: /root
  volumes:
  - name: data-path
    persistentVolumeClaim:
      claimName: data-path
