version: '3'

services:
  master:
    image: locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-rest.py --config=/mnt/locust/config --master -H http://master:8089
  
  worker:
    image: locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-rest.py --worker --master-host master