apiVersion: v1
kind: PersistentVolume
metadata:
  name: resnettracker
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/gpfs/bsc_home/xpliu/pv/resnettracker"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resnettracker
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tracker-service
  labels:
    app: scanflow-tracker
spec:
  type: NodePort
  ports:
  - nodePort: 30010
    port: 8080
    targetPort: 5000
  selector:
    app: tracker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tracker
    spec:
      volumes:
        - name: tracker
          persistentVolumeClaim:
            claimName: resnettracker
      containers:
        - image: 172.30.0.49:5000/tracker
          imagePullPolicy: IfNotPresent
          name: tracker
          resources:
           requests:
             memory: "512Mi"
             cpu: "1"
           limits:
             memory: "512Mi"
             cpu: "1"
          volumeMounts:
            - mountPath: /mlflow
              name: tracker
      restartPolicy: Always

