apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-path-graph
  namespace: resnet-tf-graph
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/gpfs/bsc_home/xpliu/inference"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-path
  namespace: resnet-tf-graph
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
