apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: example-tfserving
  annotations:
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/proxyCPU: "800m"
    sidecar.istio.io/proxyCPULimit: "800m"
    sidecar.istio.io/proxyMemory: "500Mi"
    sidecar.istio.io/proxyMemoryLimit: "500Mi"
spec:
  protocol: tensorflow
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - args:
          - --port=8500
          - --rest_api_port=8501
          - --model_name=halfplustwo
          - --model_base_path=gs://seldon-models/tfserving/half_plus_two
          image: tensorflow/serving
          name: halfplustwo
          ports:
          - containerPort: 8501
            name: http
            protocol: TCP
          - containerPort: 8500
            name: grpc
            protocol: TCP
          resources:
            limits:
              cpu: '8'
              memory: 2Gi
            requests:
              cpu: '8'
              memory: 2Gi
    graph:
      name: halfplustwo
      type: MODEL
      endpoint:
        httpPort: 8501
        grpcPort: 8500
    name: model
    replicas: 1
